codecov:
  bot: coverage
  notify:
    require_ci_to_pass: yes

coverage:
  range: 70..100
  round: up
  precision: 2

  status:
    project: yes
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, files"
  behavior: default
  require_changes: yes
